[env]
platform = teensy
board = teensy41
framework = arduino
build_flags =
  -I./
lib_deps =
  https://github.com/kalnajslab-org/SerialComm.git
  etlcpp/Embedded Template Library@20.47.1

[env:RPUComm_test]
build_src_filter =
  +<*.cpp>
  +<../examples/RPUComm_test/*.cpp>

[env:RPURecord_test]
build_flags =
  ${env.build_flags}
  -I./examples/RPURecord_test
lib_deps =
  ${env.lib_deps}
  throwtheswitch/Unity@^2.6.1
build_src_filter =
  +<*.cpp>
  +<../examples/RPURecord_test/*.cpp>
